<a href="https://colab.research.google.com/github/sambhav605/AI-License-Plate-Recognition/blob/main/day26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('customer.csv')

In [3]:
df.sample(5)

    age  gender   review education purchased
35   74    Male     Poor    School       Yes
36   34  Female     Good        UG       Yes
21   32    Male  Average        PG        No
10   98  Female     Good        UG       Yes
6    18    Male     Good    School        No

In [5]:
df = df.iloc[:,2:]

In [6]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test, y_train,y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [8]:
X_train

     review education
47     Good        PG
1      Poor        UG
26     Poor        PG
40     Good    School
45     Poor        PG
35     Poor    School
17     Poor        UG
10     Good        UG
18     Good    School
49     Good        UG
20  Average    School
48     Good        UG
37  Average        PG
3      Good        PG
8   Average        UG
36     Good        UG
27     Poor        PG
41     Good        PG
0   Average    School
43     Poor        PG
5   Average    School
28     Poor    School
34  Average    School
15     Poor        UG
46     Poor        PG
21  Average        PG
7      Poor    School
16     Poor        UG
42     Good        PG
29  Average        UG
4   Average        UG
9      Good        UG
23     Good    School
39     Poor        PG
13  Average    School
25     Good    School
14     Poor        PG
11     Good        UG
12     Poor    School
33     Good        PG

In [9]:
from sklearn.preprocessing import OrdinalEncoder

In [11]:
# create object and pass categories in order
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [12]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [16]:
# X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

In [14]:
X_train

array([[2., 2.],
       [0., 1.],
       [0., 2.],
       [2., 0.],
       [0., 2.],
       [0., 0.],
       [0., 1.],
       [2., 1.],
       [2., 0.],
       [2., 1.],
       [1., 0.],
       [2., 1.],
       [1., 2.],
       [2., 2.],
       [1., 1.],
       [2., 1.],
       [0., 2.],
       [2., 2.],
       [1., 0.],
       [0., 2.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [0., 1.],
       [0., 2.],
       [1., 2.],
       [0., 0.],
       [0., 1.],
       [2., 2.],
       [1., 1.],
       [1., 1.],
       [2., 1.],
       [2., 0.],
       [0., 2.],
       [1., 0.],
       [2., 0.],
       [0., 2.],
       [2., 1.],
       [0., 0.],
       [2., 2.]])

In [17]:
from sklearn.preprocessing import LabelEncoder

In [18]:
le = LabelEncoder()

In [19]:
le.fit(y_train)

LabelEncoder()

In [20]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [23]:
# y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [24]:
y_train

array([1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1])